extends Node
@warning_ignore("unused_signal")
signal updateAmmo(value)
@warning_ignore("unused_signal")
signal updateResp(value)
@warning_ignore("unused_signal")
signal finishing(value, enemy)
@warning_ignore("unused_signal")
signal updateScore(value)
@warning_ignore("unused_signal")
signal saveScore()
@warning_ignore("unused_signal")
signal unPaused()
@warning_ignore("unused_signal")
signal paused()
@warning_ignore("unused_signal")
signal saveWB()